repos:
  - repo: local
    hooks:
      - id: java-maven-spotless-apply
        name: Applying Spotless (re-stages files, ignore Failed)
        entry: bash -c 'mvn -q spotless:apply && git add "$@"' --
        language: system
        files: \.java$
        pass_filenames: true
      - id: java-maven-junit
        name: Running JUnit tests...
        entry: mvn test
        language: system
        pass_filenames: false
