CREATE TABLE disabled_time_slot (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    INTEGER NOT NULL,
    slot_date  DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time   TIME NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disabled_slot_item FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE,
    CONSTRAINT uq_disabled_slot UNIQUE (item_id, slot_date, start_time, end_time),
    CONSTRAINT chk_disabled_slot_time CHECK (start_time < end_time)
);

CREATE INDEX idx_disabled_slot_item_date ON disabled_time_slot(item_id, slot_date);
