ALTER TABLE item_booking DROP CONSTRAINT chk_booking_state;

ALTER TABLE item_booking ADD CONSTRAINT chk_booking_state CHECK (
    state IN (
        'BOOKING_PENDING',
        'BOOKING_CONFIRMED',
        'BOOKING_REJECTED',
        'BOOKING_CANCELLED',
        'BOOKING_COMPLETED',
        'BOOKING_PAYMENT_SUBMITTED',
        'BOOKING_PAID'
    )
);

CREATE TABLE booking_payment_proof (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    booking_id INT NOT NULL,
    uploader_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_data VARBINARY(5242880) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_booking_payment_proof PRIMARY KEY (id),
    CONSTRAINT fk_booking_payment_proof_booking FOREIGN KEY (booking_id) REFERENCES item_booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_payment_proof_uploader FOREIGN KEY (uploader_id) REFERENCES users(id),
    CONSTRAINT uq_booking_payment_proof_booking UNIQUE (booking_id)
);
