CREATE TABLE item_publication_version (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    item_id INT NOT NULL,
    owner_id INT NOT NULL,
    type_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    price_per_hour INT NOT NULL,
    capacity_people INT NOT NULL,
    max_weight_kg DECIMAL(10,2),
    difficulty_level INT,
    location_option_id INT NOT NULL,
    location_name VARCHAR(120) NOT NULL,
    cover_image_data BLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_item_publication_version PRIMARY KEY (id),
    CONSTRAINT chk_item_publication_version_price CHECK (price_per_hour >= 0),
    CONSTRAINT chk_item_publication_version_capacity CHECK (capacity_people > 0),
    CONSTRAINT chk_item_publication_version_max_weight CHECK (max_weight_kg IS NULL OR max_weight_kg > 0),
    CONSTRAINT chk_item_publication_version_difficulty CHECK (difficulty_level IS NULL OR difficulty_level BETWEEN 1 AND 5)
);

ALTER TABLE item_booking ADD COLUMN item_version_id INT;
ALTER TABLE item_booking
    ADD CONSTRAINT fk_item_booking_publication_version FOREIGN KEY (item_version_id) REFERENCES item_publication_version(id);

ALTER TABLE item_publication_version
    ADD CONSTRAINT uq_item_publication_version_id_item UNIQUE (id, item_id);

ALTER TABLE item_booking
    ADD CONSTRAINT fk_item_booking_publication_version_item
        FOREIGN KEY (item_version_id, item_id)
        REFERENCES item_publication_version(id, item_id);

CREATE INDEX idx_item_publication_version_item_id ON item_publication_version(item_id);
CREATE INDEX idx_item_publication_version_owner_id ON item_publication_version(owner_id);
CREATE INDEX idx_item_booking_item_version_id ON item_booking(item_version_id);

ALTER TABLE item_booking
    DROP CONSTRAINT fk_booking_item;

ALTER TABLE item
    DROP COLUMN owner_delete_used_at;
