CREATE TABLE "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(30),
    language VARCHAR(10) NOT NULL DEFAULT 'es',
    alias VARCHAR(30),
    password_hash VARCHAR(255),
    mail_token VARCHAR(100),
    mail_token_emitted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_language CHECK (language IN ('es', 'en'))
);

CREATE TABLE new_item_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE location (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE image (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data VARBINARY(1048576) NOT NULL
);

CREATE TABLE new_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id INT,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_item_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE TABLE "version" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INT NOT NULL,
    type_id INT NOT NULL,
    title VARCHAR(1000) NOT NULL,
    description VARCHAR(100),
    price NUMERIC(12,2) NOT NULL,
    capacity INT NOT NULL,
    weight INT NOT NULL,
    difficulty INT NOT NULL,
    location_id INT NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_v24_version_price CHECK (price >= 0),
    CONSTRAINT chk_v24_version_capacity CHECK (capacity > 0)
);

CREATE TABLE media (
    version_id INT NOT NULL,
    image_id INT NOT NULL,
    index INT NOT NULL,
    PRIMARY KEY (version_id, index)
);

CREATE TABLE availability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id INT NOT NULL,
    weekday VARCHAR(16) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT chk_v24_weekday CHECK (weekday IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT chk_v24_availability_time CHECK (start_time < end_time)
);

CREATE TABLE booking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id INT NOT NULL,
    guest_id INT,
    start TIMESTAMP NOT NULL,
    "end" TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL,
    msg VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_v24_booking_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'PAID', 'CONFIRMED', 'REFUSED', 'CANCELLED', 'FINISHED')),
    CONSTRAINT chk_v24_booking_time CHECK (start < "end")
);

CREATE TABLE payment_proof (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL UNIQUE,
    filename VARCHAR(100) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_data VARBINARY(1048576) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    refuse_msg VARCHAR(255),
    refused_at TIMESTAMP,
    reply_msg VARCHAR(255),
    replied_at TIMESTAMP
);

CREATE TABLE new_review (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    sender_id INT,
    target_type VARCHAR(16) NOT NULL,
    rating NUMERIC(2,1) NOT NULL,
    comment VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_target_type CHECK (target_type IN ('ITEM', 'USER'))
);

INSERT INTO "user" (id, first_name, last_name, email, phone, language, alias, password_hash, mail_token, mail_token_emitted_at, created_at)
SELECT id, given_name, last_name, LEFT(email, 100), phone, preferred_language, LEFT(payment_alias, 30),
       password_hash, LEFT(password_recovery_token, 100), password_recovery_used_at, created_at
FROM users;

INSERT INTO new_item_type (id, name)
SELECT id, name FROM item_type;

INSERT INTO location (id, name)
SELECT id, name FROM location_option;

INSERT INTO new_item (id, host_id, status, created_at)
SELECT i.id, ipv.owner_id, CASE WHEN ipv.active THEN 'ACTIVE' ELSE 'INACTIVE' END, ipv.item_created_at
FROM item i
JOIN item_publication_version ipv ON ipv.id = i.version_id;

INSERT INTO "version" (id, item_id, type_id, title, description, price, capacity, weight, difficulty, location_id, timezone, created_at)
SELECT ipv.id, map.item_id, ipv.type_id, ipv.title, LEFT(ipv.description, 100), ipv.price_per_hour, ipv.capacity_people,
       COALESCE(CAST(ipv.max_weight_kg AS INT), 2000), COALESCE(ipv.difficulty_level, 1), ipv.location_option_id, 'UTC', ipv.created_at
FROM item_publication_version ipv
JOIN (
    SELECT i.version_id AS ipv_id, i.id AS item_id FROM item i
    UNION
    SELECT ib.item_version_id AS ipv_id, ib.item_id AS item_id FROM item_booking ib WHERE ib.item_version_id IS NOT NULL
) map ON map.ipv_id = ipv.id;

INSERT INTO image (id, data)
SELECT id, image_data FROM item_media;

INSERT INTO media (version_id, image_id, index)
SELECT i.version_id, im.id,
       (
           SELECT COUNT(*)
           FROM item_media im2
           WHERE im2.item_id = im.item_id
             AND im2.display_order <= im.display_order
       ) - 1
FROM item_media im
JOIN item i ON i.id = im.item_id;

INSERT INTO availability (id, version_id, weekday, start_time, end_time)
SELECT ia.id, i.version_id, ia.weekday, ia.start_time, ia.end_time
FROM item_availability ia
JOIN item i ON i.id = ia.item_id;

INSERT INTO booking (id, version_id, guest_id, start, "end", status, msg, created_at, updated_at)
SELECT ib.id,
       COALESCE(ib.item_version_id, i.version_id),
       ib.guest_id,
       ib.start_time,
       ib.end_time,
       CASE ib.state
           WHEN 'BOOKING_PENDING' THEN 'PENDING'
           WHEN 'BOOKING_CONFIRMED' THEN 'ACCEPTED'
           WHEN 'BOOKING_REJECTED' THEN 'REJECTED'
           WHEN 'BOOKING_CANCELLED' THEN 'CANCELLED'
           WHEN 'BOOKING_COMPLETED' THEN 'FINISHED'
           WHEN 'BOOKING_PAYMENT_SUBMITTED' THEN 'PAID'
           WHEN 'BOOKING_PAID' THEN 'CONFIRMED'
           WHEN 'BOOKING_PAYMENT_REFUSED' THEN 'REFUSED'
       END,
       LEFT(ib.request_message, 255),
       ib.created_at,
       ib.updated_at
FROM item_booking ib
LEFT JOIN item i ON i.id = ib.item_id
WHERE COALESCE(ib.item_version_id, i.version_id) IS NOT NULL;

INSERT INTO payment_proof (id, booking_id, filename, content_type, file_data, created_at, refuse_msg, refused_at, reply_msg, replied_at)
SELECT id, booking_id, LEFT(file_name, 100), content_type, file_data, created_at,
       LEFT(refusal_reason, 255), refused_at, LEFT(guest_reply, 255), NULL
FROM booking_payment_proof;

INSERT INTO new_review (id, booking_id, sender_id, target_type, rating, comment, created_at)
SELECT id, booking_id, reviewer_user_id, target_type, rating, LEFT(comment, 255), created_at
FROM review;

ALTER TABLE new_item ADD CONSTRAINT fk_v24_item_host FOREIGN KEY (host_id) REFERENCES "user"(id) ON DELETE SET NULL;
ALTER TABLE "version" ADD CONSTRAINT fk_v24_version_item FOREIGN KEY (item_id) REFERENCES new_item(id) ON DELETE CASCADE;
ALTER TABLE "version" ADD CONSTRAINT fk_v24_version_type FOREIGN KEY (type_id) REFERENCES new_item_type(id);
ALTER TABLE "version" ADD CONSTRAINT fk_v24_version_location FOREIGN KEY (location_id) REFERENCES location(id);
ALTER TABLE media ADD CONSTRAINT fk_v24_media_version FOREIGN KEY (version_id) REFERENCES "version"(id) ON DELETE CASCADE;
ALTER TABLE media ADD CONSTRAINT fk_v24_media_image FOREIGN KEY (image_id) REFERENCES image(id) ON DELETE CASCADE;
ALTER TABLE availability ADD CONSTRAINT fk_v24_availability_version FOREIGN KEY (version_id) REFERENCES "version"(id) ON DELETE CASCADE;
ALTER TABLE booking ADD CONSTRAINT fk_v24_booking_version FOREIGN KEY (version_id) REFERENCES "version"(id) ON DELETE CASCADE;
ALTER TABLE booking ADD CONSTRAINT fk_v24_booking_guest FOREIGN KEY (guest_id) REFERENCES "user"(id) ON DELETE SET NULL;
ALTER TABLE payment_proof ADD CONSTRAINT fk_v24_payment_proof_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE;
ALTER TABLE new_review ADD CONSTRAINT fk_v24_review_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE;
ALTER TABLE new_review ADD CONSTRAINT fk_v24_review_sender FOREIGN KEY (sender_id) REFERENCES "user"(id) ON DELETE SET NULL;

DROP TABLE review;
DROP TABLE booking_payment_proof;
DROP TABLE item_booking;
DROP TABLE item_availability;
DROP TABLE item_media;
DROP TABLE item;
DROP TABLE item_publication_version;
DROP TABLE location_option;
DROP TABLE item_type;
DROP TABLE users;

ALTER TABLE new_item_type RENAME TO item_type;
ALTER TABLE new_item RENAME TO item;
ALTER TABLE new_review RENAME TO review;

-- Backward-compatible views for existing HSQL tests that still use old names/columns.
CREATE VIEW users AS
SELECT
    id,
    created_at,
    first_name AS given_name,
    last_name,
    email,
    phone,
    language AS preferred_language,
    alias AS payment_alias,
    password_hash,
    mail_token AS password_recovery_token,
    mail_token_emitted_at AS password_recovery_used_at
FROM "user";

CREATE VIEW location_option AS
SELECT id, name
FROM location;
