CREATE TABLE location_option (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT pk_location_option PRIMARY KEY (id),
    CONSTRAINT uq_location_option_name UNIQUE (name)
);

INSERT INTO location_option (name) VALUES
    ('Portezuelo'),
    ('Club Nordelta (Sede Central)'),
    ('Los Castores'),
    ('Cabos del Lago'),
    ('La Isla'),
    ('Puerto Canoas'),
    ('Yoo'),
    ('El Golf'),
    ('Islas del Golf'),
    ('Virazon'),
    ('El Muelle'),
    ('Nordelta Rio / Bahia Grande'),
    ('El Yacht');
